spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: sagar
    password: sagar123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/bankdb
    user: sagar
    password: sagar123
    locations: classpath:db/migration
